# Generated by Django 5.1.3 on 2024-11-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название хотелки')),
                ('description', models.CharField(max_length=500, verbose_name='Подробное описание')),
                ('price', models.IntegerField()),
                ('is_complete', models.BooleanField(default=False, verbose_name='Закрыто')),
            ],
            options={
                'verbose_name': 'Желание',
                'verbose_name_plural': 'Желания',
            },
        ),
    ]
